services:
  app: &app
    image: node:lts-slim
    working_dir: /app
    volumes:
      - ./app:/app:cached
    ports:
      - 8080:8080
      - 3000:3000
    tty: true

  setup:
    image: busybox
    depends_on:
      - setup-node_module
  setup-node_module:
    <<: *app
    command: cp .env.example .env.production  && npm ci
